spring.application.name=M1_REST

spring.datasource.url=jdbc:mysql://localhost:3307/m1rest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

baseurl=http://localhost:8081


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testsubhabrata736@gmail.com
spring.mail.password=betu zmob tjmi barg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.boot.admin.client.url=http://localhost:9090


# Force correct access URLs for Actuator
spring.boot.admin.client.instance.service-url=http://localhost:8080/
spring.boot.admin.client.instance.management-url=http://localhost:8080/actuator
spring.boot.admin.client.instance.health-url=http://localhost:8080/actuator/health



